### ISSUE TITLE
Adobe Analytics getTracker

### ISSUE THREAD

**Issue by marcin-j** [adobe/reactor-sandbox#41]
Hey, is there a way to retrieve tracker in sandbox environment? Somehow attaching Adobe Analytics extension to our sandbox environment?

Thanks, Marcin

**Comment by Aaronius** [comment]
No, sorry. Usually when I'm testing integrations with other extensions, I ditch the sandbox and instead upload my extension to Launch and go through the process of publishing a library with both extensions in it. In case it helps, I usually create a file named something like `upload.sh` that looks like this:

```
#!/bin/sh

npx @adobe/reactor-packager && npx @adobe/reactor-uploader --org-id=XXX@AdobeOrg --tech-account-id=XXX@techacct.adobe.com --api-key=XXX
```

That way, I can quickly package and upload my extension just by running the file.
