### ISSUE TITLE
Automated Testing Example

### ISSUE THREAD

**Issue by db798** [adobe/reactor-sandbox#54]
Would it be possible for someone to share an example of using cypress to test within the sandboxed environment? 

We have the sandbox running but are unable to access `loadExtensionView`

```
it('basic test', () => {
    cy.visit('/viewSandbox.html');
    
    const window = cy.window();

    window.loadExtensionView({ viewPath: 'file.html' })
      .then(view => view.getSettings())
      .then(settings => expect(settings).toEqual({ foo: 'bar' }));
  });
```

The above code open the page as expected but fail while trying to execute `loadExtensionView` - `window.loadExtensionView is not a function`.

Also in the console we are seeing the following error - `configuration.html:4 Uncaught DOMException: Failed to set the 'domain' property on 'Document': Assignment is forbidden for sandboxed iframes`

We're likely missing something obvious so an example would be much appreciated.

**Comment by thebenrob** [comment]
Preliminary feedback from the engineering team is that there's no reason that you shouldn't be able to do this.  Can you provide more information about the command you're using to start the sandbox as well as the Cypress baseUrl defined in the Cypress configuration?

**Comment by db798** [comment]
Apologies for the slow response, we actually switched to using protractor and we able to get some tests up and running. 

This is a sample of the protractor code for reference, not very nice but allows us to test things.

``` 
  it('getSettings should return correct value when settings are passed into init function', async function () {
    await browser.get('http://localhost:3000/viewSandbox.html');

    const passInSettingsOnInit = `return await window.loadExtensionView({
      viewPath: 'sample.html'
    }).then(extensionView => {
      extensionView.init({
        "settings": {
          "property1": "test",
          "attributes": {
            "key": "value"
          }
        }
      });

      return extensionView.getSettings();
    });`;

    await browser.executeScript(passInSettingsOnInit).then(function (settings) {
      return expect(settings).eql({
        property1: "test"
        attributes: {
          key: 'value'
        }
      });
    });
  });
```

And just to answer your questions, we are using `npx @adobe/reactor-sandbox` to start the sandbox and the baseUrl would have been `http://localhost:3000/`. Even when we were having issue with cypress the sandbox was running and the page was opening as expected. 

We generally don't use cypress so it's likely we were just missing something on the test framework side

**Comment by thebenrob** [comment]
@db798 I'm going to go ahead and close this ticket then, since you're not using Cypress anymore.
