### ISSUE TITLE
Mobile Platform Compatibility

### ISSUE THREAD

**Issue by dgrossen** [adobe/reactor-sandbox#58]
### Expected Behaviour

The sandbox caters to help mobile developers build extensions, rules, data elements and other launch entities that are unique to the mobile platform. 

### Actual Behaviour

The sandbox is mostly driven by a web or edge experience.

The following are some examples of mobile incompatibilities (including but not limited to)

#### Rule Building

- `Page Top` and `Click` are offered as events
- 'Log Event Info' is offered as an action

Saving a rule appears to assume either the edge or web schemas:

`Cannot read property 'transforms' of undefined`

#### Data Elements

- `Local Storage` and `JavaScript Variable` are offered as types

### Reproduce Scenario (including but not limited to)

Git clone https://github.com/adobe/reactor-mobile-examples/tree/master/weather-extension

Update the Reactor Sandbox lib to 11.x

Run the sandbox

#### Steps to Reproduce

Run the sandbox and view some of the defaults offered to a mobile extension.

Try to build and save a rule and observe the `Cannot read property 'transforms' of undefined` error.

**Comment by brenthosie** [comment]
@adobe export issue to Jira project PDCL as Bug
