### ISSUE TITLE
Fatal error on running npx init command

### ISSUE THREAD

**Issue by rfreemo** [adobe/reactor-sandbox#80]
### Expected Behaviour

On running _npx @adobe/reactor-sandbox init_ the sandbox is created and available on 3000 / 4000.

### Actual Behaviour

immediate exit and error:

```
Error:

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '../../app/constants'
```

#### Steps to Reproduce / Environment

Node version 16.3.2, npm 8.4.1, Mac OS

Run _npx @adobe/reactor-sandbox init_

or in a clean Ubuntu install (using docker)

docker container run --interactive --tty --rm ubuntu bash

apt update
apt install nodejs npm

npx @adobe/reactor-sandbox init

#### Misc

See also (Adobe internal) https://adobe-acs.slack.com/archives/CA8J290S1/p1647233597259119

#### Workaround

Use previous version: _npx @adobe/reactor-sandbox@12.2.1 init_

**Comment by brenthosie** [comment]
Thanks for the report and sorry for the problem. For now, use the `v12.2.1` release
